# Generated by Django 6.0.3 on 2026-03-31 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Mesh', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(choices=[('FREE', 'Free'), ('TRIAL', 'Trial'), ('PREMIUM', 'Premium'), ('CANCELLED', 'Cancelled')], default='FREE', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('public_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('LINUX', 'Linux'), ('WINDOWS', 'Windows')], max_length=20)),
                ('wireguard_ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.ecosystem')),
            ],
        ),
        migrations.AddField(
            model_name='ecosystem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecosystems', to='api.user'),
        ),
    ]
